toDoTracker/mysite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('toDoTracker.urls'))
]

toDoTracker/toDoTracker/urls.py
from django.urls import path

from . import views


app_name = 'toDoTracker'
urlpatterns = [
    path('myToDos/', views.mytodos, name='myToDos'),
    path('myToDos/add/', views.add, name='add'),
    path('myToDos/impressum/', views.impressum, name='impressum'),
    path('myToDos/delete/todo<int:todo_id>/', views.delete, name='delete'),
    path('myToDos/edit/todo<int:todo_id>/', views.edit, name='edit'),
]

toDoTracker/toDoTracker/models.py
from django.db import models

# Create your models here.


class ToDo(models.Model):

    toDo_text = models.CharField(max_length=160)
    due_date = models.DateTimeField()
    progress = models.IntegerField(default=0)

    def __str__(self):
        return self.toDo_text

toDoTracker/toDoTracker/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from .models import ToDo


def mytodos(request):
    todo_queryset = ToDo.objects.all().order_by('due_date')
    context = {'todo_queryset' : todo_queryset}
    return render(request, 'toDoTracker/index.html', context)


def delete(request, todo_id):
    item = get_object_or_404(ToDo, pk=todo_id)
    item.delete()
    return redirect(reverse('toDoTracker:myToDos'))


def add(request):
    if request.method == "GET":
        return render(request, 'toDoTracker/addTODO.html')
    elif request.method == "POST":
        ToDo.objects.create(toDo_text=request.POST['todo_text'], due_date=request.POST['date'],\
                            progress=request.POST['progress'])
        return redirect(reverse('toDoTracker:myToDos'))


def edit(request, todo_id):
    if request.method == "GET":
        item = get_object_or_404(ToDo, pk=todo_id)
        return render(request, 'toDoTracker/editTODO.html', {'item' :item})
    elif request.method == "POST":
        ToDo.objects.filter(id=todo_id).update(toDo_text=request.POST['todo_text'], due_date=request.POST['date'],
                                               progress=request.POST['progress'])
        return redirect(reverse('toDoTracker:myToDos'))


def impressum(request):
    return render(request, 'toDoTracker/impressum.html')

toDoTracker/toDoTracker/templates/toDoTracker/addTODO.html
{% extends 'toDoTracker/base.html' %}

{% block content %}
    <main>
        <h2>Add TODO</h2>
        <form class="form" action="{% url 'toDoTracker:add' %}" method="post">{% csrf_token %}
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>TODO</th>
                            <th>Deadline</th>
                            <th>Done(%)</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr><td><textarea class = "form-control" name="todo_text" rows = "1" maxlength="160" placeholder="Your TODO" required></textarea></td>
                            <td><input type="date" class="calender form-control" name="date" required></input></td>
                            <td><input type="range" name="progress" value="0" min="0" max="100" class="range form-control"></input></td>
                            <td><button type="submit" class="btn btn-outline-dark" name = "add">Add</button></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </form>
    </main>
{% endblock %}

toDoTracker/toDoTracker/templates/toDoTracker/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!-- Load css sheet -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'toDoTracker/todos.css' %}" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="icon" type="image/svg+xml" href="favicon.svg" sizes="any">

    <title>TODO-Tracker</title>
  </head>

  <body>
     <!--Menu to navigate to subpages-->
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <a class="navbar-brand">TODO-Tracker</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar1" aria-controls="navbar1" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbar1">
        <ul class="navbar-nav">
          <li class="nav-item"><a class="nav-link" href="{% url 'toDoTracker:myToDos' %}">My TODOs</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'toDoTracker:add' %}">Add new TODO</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'toDoTracker:impressum' %}">Impressum</a></li>
        </ul>
      </div>
    </nav>
    <!-- End of Navbar -->

    {% block content %}
    {% endblock %}

     <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

toDoTracker/toDoTracker/templates/toDoTracker/editTODO.html
{% extends 'toDoTracker/base.html' %}
<script>
    this.form.elements["todo_text"].value = ;
</script>

{% block content %}
    <main>
        <h2>Edit TODO</h2>
        <form class="form" action="{% url 'toDoTracker:edit' item.id %}" method="post">{% csrf_token %}
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>TODO</th>
                            <th>Deadline</th>
                            <th>Done(%)</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr><td><textarea class = "form-control" name="todo_text" rows = "1" maxlength="160" required >{{item.toDo_text}}</textarea></td>
                            <td><input type="date" class="calender form-control" name="date" value = {{ item.due_date | date:"Y-m-d" }} required ></input></td>
                            <td><input type="range" name="progress" value = "{{item.progress}}" min="0" max="100" class="range form-control"></input></td>
                            <td><button type="submit" class="btn btn-outline-dark" name = "done">Done</button></td>
                            <td><button type="submit" class="btn btn-outline-dark" name = "cancel" formaction="{% url 'toDoTracker:myToDos'%}">Cancel</button></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </form>
    </main>
{% endblock %}

toDoTracker/toDoTracker/templates/toDoTracker/impressum.html
{% extends 'toDoTracker/base.html' %}

{% block content %}
         <main>
            <h2>Impressum</h2>
            <p class="lead">
                <strong>Authors:</strong>
                <ul>
                    <li>Jamina Darskus</li>
                    <li>Olivia Dargel</li>
                </ul>
            </p>
        </main>
{% endblock %}

toDoTracker/toDoTracker/templates/toDoTracker/index.html
{% extends 'toDoTracker/base.html' %}

{% block content %}
  <main>
        <h2>My TODOs</h2>
        <div class = "table-responsive">
          <table class="table table-hover">
              <thead>
                <tr>
                  <th>TODO</th>
                  <th>Deadline</th>
                  <th>Done (%)</th>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                   {% for item in todo_queryset %}
                      <tr>
                          <td>{{ item.toDo_text }}</td>
                          <td>{{ item.due_date | date:"F d Y" }}</td>
                          <td>{{ item.progress }}%</td>
                          <td>
                            <a href="{% url 'toDoTracker:edit' item.id %}" class='btn btn-outline-dark'>Edit</a>
                          </td>
                          <td>
                            <a href="{% url 'toDoTracker:delete' item.id %}" class='btn btn-outline-dark'>Delete</a>
                          </td>
                      </tr>
                   {% endfor %}
              </tbody>
          </table>
        </div>
    </main>
{% endblock %}